### ISSUE TITLE
copilot crashes after probing servers

### ISSUE THREAD

**Issue by SalsaBr** [pcuzner/ceph-ansible-copilot#8]
I've hit an app crash after checking for servers' access and then when I hit 'probe', application crashes and dumps this message:

# copilot
Traceback (most recent call last):
  File "/usr/local/bin/copilot", line 4, in <module>
    __import__('pkg_resources').run_script('copilot==0.9.5', 'copilot')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/copilot-0.9.5-py2.7.egg/EGG-INFO/scripts/copilot", line 465, in <module>
    
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 825, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 2271, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 837, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1590, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 622, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 407, in keypress
    key = self.__super.keypress(size, key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1590, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 622, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 2271, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python2.7/dist-packages/urwid/wimp.py", line 540, in keypress
    self._emit('click')
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 460, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python2.7/dist-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python2.7/dist-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "build/bdist.linux-x86_64/egg/ceph_ansible_copilot/ui/host_validation.py", line 54, in probe
  File "build/bdist.linux-x86_64/egg/ceph_ansible_copilot/ansible/playbook.py", line 177, in __init__
AttributeError: can't set attribute

I'm using copilot master branch

**Comment by Haribo112** [comment]
I have this exact issue. Any ideas?

**Comment by SalsaBr** [comment]
Sorry, never managed to analyse correctly nor solve it. In the end I had other priorities and decided to take a more proven approach to install ceph and forgot about this.
